version: '{branch}#{build}'
image: Visual Studio 2013
clone_folder: c:/projects/ews-cpp-64-12
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: >-
    cd C:\projects\ews-cpp-64-12\scripts

    sed -e s/14/12/g build-curl.bat > build.bat

    set ERRORLEVEL=0

    build.bat

    set ERRORLEVEL=""

    cd ..

    cmake -Bbuild -H. -G "Visual Studio 12 2013 Win64" -DCURL_LIBRARY="C:\projects\ews-cpp-64-12\scripts\win64-debug\lib\libcurl_debug.lib" -DCURL_INCLUDE_DIR="C:\projects\ews-cpp-64-12\scripts\win64-debug\include"


    cd build

    cmake --build .