---
before_script:
  - "sudo apt-get install libcurl4-gnutls-dev"
  - "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .."
cache: apt
compiler:
  - gcc
dist: xenial
language: cpp
os:
  - linux
script:
  - "if [ \"$CXX\" = \"g++\" ]; then cmake --build build_gcc; fi"
sudo: required

